// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkHZi_hYUlbNmU1m4ejhAHRlhUTA2-Pog',
    appId: '1:431784510650:web:545f2627d44e747e996e83',
    messagingSenderId: '431784510650',
    projectId: 'study-smart-bccfa',
    authDomain: 'study-smart-bccfa.firebaseapp.com',
    storageBucket: 'study-smart-bccfa.firebasestorage.app',
    measurementId: 'G-L2SNVTDZPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEUQJu5SJmVBkEu3u8gPxbH8Zn0wcHQbI',
    appId: '1:431784510650:android:94ab6a3c348f131c996e83',
    messagingSenderId: '431784510650',
    projectId: 'study-smart-bccfa',
    storageBucket: 'study-smart-bccfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHK0Ws7uj8oJsug0fo-eMYltjVe6bDpBc',
    appId: '1:431784510650:ios:c35477c123ea3a60996e83',
    messagingSenderId: '431784510650',
    projectId: 'study-smart-bccfa',
    storageBucket: 'study-smart-bccfa.firebasestorage.app',
    iosBundleId: 'com.studysmart.studySmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHK0Ws7uj8oJsug0fo-eMYltjVe6bDpBc',
    appId: '1:431784510650:ios:c35477c123ea3a60996e83',
    messagingSenderId: '431784510650',
    projectId: 'study-smart-bccfa',
    storageBucket: 'study-smart-bccfa.firebasestorage.app',
    iosBundleId: 'com.studysmart.studySmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkHZi_hYUlbNmU1m4ejhAHRlhUTA2-Pog',
    appId: '1:431784510650:web:f5fa1105efa7f37a996e83',
    messagingSenderId: '431784510650',
    projectId: 'study-smart-bccfa',
    authDomain: 'study-smart-bccfa.firebaseapp.com',
    storageBucket: 'study-smart-bccfa.firebasestorage.app',
    measurementId: 'G-WVENEYRNKQ',
  );
}
